name: Test

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  pull_request:

env:
  PYTHON_VERSION: '3.9.13'

jobs:
  mypy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
            pip3 install wheel
            pip3 install -r requirements-dev.txt

      - name: Run mypy
        run: mypy aoirint_matvtool

  mypy-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
            pip3 install wheel
            pip3 install -r requirements-dev.txt

      - name: Run mypy
        run: mypy tests

  pytest:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-20.04'
          - os: 'ubuntu-22.04'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
            pip3 install wheel
            pip3 install -r requirements-dev.txt

      - name: Install FFmpeg
        run: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg

      - name: FFmpeg Version
        run: |
            ffmpeg -version

      - name: Run pytest
        run: pytest tests
